[env]

# FFMPEG Libraries
FFMPEG_STATIC = "1"
FFMPEG_INCLUDE_DIR = { value = "bin/ffmpeg-6.1/mac-arm64/include/", relative = true}
FFMPEG_LIB_DIR = { value = "bin/ffmpeg-6.1/mac-arm64/lib/", relative = true}

# Apple Silicon
FFMPEG_INCLUDE_DIR_AARCH64_APPLE_DARWIN = { value = "bin/ffmpeg-6.1/mac-arm64/include/", relative = true}
FFMPEG_LIB_DIR_AARCH64_APPLE_DARWIN = { value = "bin/ffmpeg-6.1/mac-arm64/lib/", relative = true}

# Windows x86_64, MSVC
FFMPEG_INCLUDE_DIR_X86_64_PC_WINDOWS_MSVC = { value = "bin/ffmpeg-6.1/win-x86/include/", relative = true}
FFMPEG_LIB_DIR_X86_64_PC_WINDOWS_MSVC = { value = "bin/ffmpeg-6.1/win-x86/lib/", relative = true}
